/*
 *Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 *Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package brigada11.lab3;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.event.TableModelEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.UnsupportedLookAndFeelException;


/**
 *
 * @author Danila
 */
 
public class NewJFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(NewJFrame.class.getName());

    /**
     * Creates new form NewJFrame
     */
    private List<RecIntegral> records = new ArrayList<>();
    
    private void showError(String message) {
        JOptionPane.showMessageDialog(this, 
            message, 
            "Ошибка ввода", 
            JOptionPane.ERROR_MESSAGE);
    }
    
    private void setupTable() {
    DefaultTableModel model = (DefaultTableModel) tabl.getModel();
    
    // Слушатель для обновления коллекции при редактировании таблицы
    model.addTableModelListener((TableModelEvent e) -> {
        if (e.getType() == TableModelEvent.UPDATE) {
            int row = e.getFirstRow();
            int column = e.getColumn();
            
            if (row >= 0 && column >= 0 && column < 3 && row < records.size()) {
                try {
                    double lower = Double.parseDouble(model.getValueAt(row, 0).toString());
                    double upper = Double.parseDouble(model.getValueAt(row, 1).toString());
                    double step = Double.parseDouble(model.getValueAt(row, 2).toString());
                    
                    // Проверяем корректность значений
                    if (step <= 0) {
                        throw new CustomException("Шаг должен быть положительным числом!");
                    }
                    
                    RecIntegral rec = records.get(row);
                    
                    // Обновляем значения с проверкой
                    try {
                        rec.setLower(lower);
                        rec.setUpper(upper);
                        rec.setStep(step);
                        rec.setResult(0);
                        model.setValueAt("", row, 3);
                    } catch (CustomException ex) {
                        // Восстанавливаем старое значение в таблице
                        model.setValueAt(rec.getLower(), row, 0);
                        model.setValueAt(rec.getUpper(), row, 1);
                        model.setValueAt(rec.getStep(), row, 2);
                        showError(ex.getMessage());
                    }
                    
                } catch (NumberFormatException ex) {
                    showError("Ошибка формата числа! Введите корректное число.");
                } catch (CustomException ex) {
                    showError(ex.getMessage());
                }
            }
        }
    });
}

    public NewJFrame() {
        records = new ArrayList<>();
        initComponents();
        setupTable();
    }    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        save = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        calculate = new javax.swing.JButton();
        tablica = new javax.swing.JScrollPane();
        tabl = new javax.swing.JTable();
        verhpor = new javax.swing.JTextField();
        nizpor = new javax.swing.JTextField();
        shag = new javax.swing.JTextField();
        vp = new javax.swing.JLabel();
        np = new javax.swing.JLabel();
        sh = new javax.swing.JLabel();
        fill = new javax.swing.JButton();
        clear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Лабораторная работа 3 [1/x]");

        save.setText("Записать");
        save.addActionListener(this::saveActionPerformed);

        delete.setText("Удалить");
        delete.addActionListener(this::deleteActionPerformed);

        calculate.setText("Вычислить");
        calculate.addActionListener(this::calculateActionPerformed);

        tabl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ниж. порог", "Верх. порог", "Шаг", "Результат"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                true, true, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablica.setViewportView(tabl);

        verhpor.addActionListener(this::verhporActionPerformed);

        nizpor.addActionListener(this::nizporActionPerformed);

        vp.setText("Верхний порог");

        np.setText("Нижний порог");

        sh.setText("Шаг");

        fill.setText("Заполнить из коллекции");
        fill.addActionListener(this::fillActionPerformed);

        clear.setText("Очистить таблицу");
        clear.addActionListener(this::clearActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tablica, javax.swing.GroupLayout.DEFAULT_SIZE, 572, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(vp)
                    .addComponent(sh, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(np))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(verhpor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                    .addComponent(nizpor, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(shag))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(calculate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(save, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(delete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(fill, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(clear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(save)
                    .addComponent(fill)
                    .addComponent(np)
                    .addComponent(nizpor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(delete)
                    .addComponent(clear)
                    .addComponent(verhpor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vp))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(calculate)
                    .addComponent(shag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sh))
                .addGap(43, 43, 43)
                .addComponent(tablica, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
       int selectedRow = tabl.getSelectedRow();
        if (selectedRow >= 0) {
            if (selectedRow < records.size()) {
                records.remove(selectedRow);
            }
            
            DefaultTableModel model = (DefaultTableModel) tabl.getModel();
            model.removeRow(selectedRow);
            
        } else {
            showError("Выберите строку для удаления!");
        }                                       
    
    }//GEN-LAST:event_deleteActionPerformed

    private void calculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateActionPerformed
        // TODO add your handling code here:
    int selectedRow = tabl.getSelectedRow();
        
        if (selectedRow >= 0) {
            try {
                DefaultTableModel model = (DefaultTableModel) tabl.getModel();
                
                double lower = Double.parseDouble(model.getValueAt(selectedRow, 0).toString());
                double upper = Double.parseDouble(model.getValueAt(selectedRow, 1).toString()); 
                double step = Double.parseDouble(model.getValueAt(selectedRow, 2).toString());       
                
                double result = calculateIntegral(lower, upper, step);
                
                if (selectedRow < records.size()) {
                    RecIntegral rec = records.get(selectedRow);
                    rec.setLower(lower);
                    rec.setUpper(upper);
                    rec.setStep(step);
                    rec.setResult(result);
                }
                
                model.setValueAt(String.format("%.6f", result), selectedRow, 3);
                
            } catch (NumberFormatException ex) {
                showError("Ошибка в данных строки!");
            } catch (CustomException ex) {
                showError(ex.getMessage());
            }
        }
    }

private double calculateIntegral(double a, double b, double h) {
    java.util.function.DoubleUnaryOperator f = x -> 1/x;
    
    double sum = 0;
    double currentX = a;
    
    while (currentX < b) {
        double nextX = currentX + h;

        if (nextX > b) {
            h = b - currentX;
            nextX = b;
        }

        sum += (f.applyAsDouble(currentX) + f.applyAsDouble(nextX)) * h / 2.0;
        
        currentX = nextX;
    }
    
    return sum;
    }//GEN-LAST:event_calculateActionPerformed

    @SuppressWarnings("empty-statement")
    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:
       try {
            double lower = Double.parseDouble(nizpor.getText());
            double upper = Double.parseDouble(verhpor.getText());
            double step = Double.parseDouble(shag.getText());
            
            // Проверяем шаг отдельно
            RecIntegral.validateStep(step);
            
            // Создаем запись с проверкой в конструкторе
            RecIntegral record = new RecIntegral(lower, upper, step, 0);
            records.add(record);
            
            DefaultTableModel model = (DefaultTableModel) tabl.getModel();
            model.addRow(new Object[]{lower, upper, step, ""});
            
            nizpor.setText("");
            verhpor.setText("");
            shag.setText("");
            
        } catch (NumberFormatException ex) {
            showError("Введите корректные числа!");
        } catch (CustomException ex) {
            showError(ex.getMessage());
        }
    }//GEN-LAST:event_saveActionPerformed

    private void verhporActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verhporActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_verhporActionPerformed

    private void fillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fillActionPerformed
        // TODO add your handling code here:
         DefaultTableModel model = (DefaultTableModel) tabl.getModel();
        
        model.setRowCount(0);
        
        // Заполняем данными из коллекции
        for (RecIntegral rec : records) {
            String result = rec.getResult() == 0 ? "" : String.format("%.6f", rec.getResult());
            model.addRow(new Object[]{
                rec.getLower(),
                rec.getUpper(),
                rec.getStep(),
                result
            });
        }  
    }//GEN-LAST:event_fillActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:
        
        DefaultTableModel model = (DefaultTableModel) tabl.getModel();
        model.setRowCount(0);

    }//GEN-LAST:event_clearActionPerformed

    private void nizporActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nizporActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nizporActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, (UnsupportedLookAndFeelException) ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new NewJFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton calculate;
    private javax.swing.JButton clear;
    private javax.swing.JButton delete;
    private javax.swing.JButton fill;
    private javax.swing.JTextField nizpor;
    private javax.swing.JLabel np;
    private javax.swing.JButton save;
    private javax.swing.JLabel sh;
    private javax.swing.JTextField shag;
    private javax.swing.JTable tabl;
    private javax.swing.JScrollPane tablica;
    private javax.swing.JTextField verhpor;
    private javax.swing.JLabel vp;
    // End of variables declaration//GEN-END:variables

}
