/*
 *Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 *Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package brigada11.lab2;

import javax.swing.JOptionPane;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;
import java.util.List;
import javax.swing.UnsupportedLookAndFeelException;


/**
 *
 * @author Danila
 */
 
public class NewJFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(NewJFrame.class.getName());

    /**
     * Creates new form NewJFrame
     */
    private List<RecIntegral> records = new ArrayList<>();
    
    private void setupTable() {
        DefaultTableModel model = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return column < 3;
            }
        };
        
        model.addColumn("Нижний предел");  
        model.addColumn("Верхний предел");   
        model.addColumn("шаг");             
        model.addColumn("Результат");       
        
        tabl.setModel(model);
        
        // Обновление
        model.addTableModelListener(new TableModelListener() {
            @Override
            public void tableChanged(TableModelEvent e) {
                if (e.getType() == TableModelEvent.UPDATE) {
                    int row = e.getFirstRow();
                    int column = e.getColumn();
                    
                    if (row >= 0 && column >= 0 && column < 3 && row < records.size()) {
                        try {
                            double lower = Double.parseDouble(model.getValueAt(row, 0).toString());
                            double upper = Double.parseDouble(model.getValueAt(row, 1).toString());
                            double step = Double.parseDouble(model.getValueAt(row, 2).toString());
                            
                            RecIntegral rec = records.get(row);
                            rec.setLower(lower);
                            rec.setUpper(upper);
                            rec.setStep(step);
                            rec.setResult(0);
                            
                            model.setValueAt("", row, 3);
                        } catch (NumberFormatException ex) {
                        }
                    }
                }
            }
        });
    }
    
    public NewJFrame() {
        records = new ArrayList<>();
        
        initComponents();
        setupTable();
    }    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        save = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        calculate = new javax.swing.JButton();
        tablica = new javax.swing.JScrollPane();
        tabl = new javax.swing.JTable();
        verhpor = new javax.swing.JTextField();
        nizpor = new javax.swing.JTextField();
        shag = new javax.swing.JTextField();
        vp = new javax.swing.JLabel();
        np = new javax.swing.JLabel();
        sh = new javax.swing.JLabel();
        fill = new javax.swing.JButton();
        clear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Лабораторная работа 2 [1/x]");

        save.setText("Записать");
        save.addActionListener(this::saveActionPerformed);

        delete.setText("Удалить");
        delete.addActionListener(this::deleteActionPerformed);

        calculate.setText("Вычислить");
        calculate.addActionListener(this::calculateActionPerformed);

        tabl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ниж. порог", "Верх. порог", "Шаг", "Результат"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                true, true, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablica.setViewportView(tabl);

        verhpor.addActionListener(this::verhporActionPerformed);

        nizpor.addActionListener(this::nizporActionPerformed);

        vp.setText("Верхний порог");

        np.setText("Нижний порог");

        sh.setText("Шаг");

        fill.setText("Заполнить из коллекции");
        fill.addActionListener(this::fillActionPerformed);

        clear.setText("Очистить таблицу");
        clear.addActionListener(this::clearActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tablica, javax.swing.GroupLayout.DEFAULT_SIZE, 572, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(vp)
                    .addComponent(sh, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(np))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(verhpor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                    .addComponent(nizpor, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(shag))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(calculate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(save, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(delete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(fill, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(clear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(save)
                    .addComponent(fill)
                    .addComponent(np)
                    .addComponent(nizpor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(delete)
                    .addComponent(clear)
                    .addComponent(verhpor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vp))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(calculate)
                    .addComponent(shag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sh))
                .addGap(43, 43, 43)
                .addComponent(tablica, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
       int selectedRow = tabl.getSelectedRow();
    
        // Проверяем, выбрана ли строка
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Выберите строку для удаления!", 
                "Ошибка", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        try {
        // Получаем индекс строки в модели
        int modelIndex = tabl.convertRowIndexToModel(selectedRow);
        
        // Получаем модель таблицы
        DefaultTableModel model = (DefaultTableModel) tabl.getModel();
        
        // Проверяем, что модель не null
        if (model == null) {
            JOptionPane.showMessageDialog(this, "Ошибка доступа к модели таблицы",
                "Ошибка", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // Удаляем строку из модели
        model.removeRow(modelIndex);
        
        // Обновляем таблицу
        tabl.revalidate();
        tabl.repaint();
        
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Произошла ошибка при удалении строки",
            "Ошибка", JOptionPane.ERROR_MESSAGE);
    }
    
    }//GEN-LAST:event_deleteActionPerformed

    private void calculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateActionPerformed
        // TODO add your handling code here:
    int selectedRow = tabl.getSelectedRow();
        
        if (selectedRow >= 0) {
            try {
                DefaultTableModel model = (DefaultTableModel) tabl.getModel();
                
                double lower = Double.parseDouble(model.getValueAt(selectedRow, 0).toString());
                double upper = Double.parseDouble(model.getValueAt(selectedRow, 1).toString()); 
                double step = Double.parseDouble(model.getValueAt(selectedRow, 2).toString());       
                
                double result = calculateIntegral(lower, upper, step);
                
                if (selectedRow < records.size()) {
                    RecIntegral rec = records.get(selectedRow);
                    rec.setLower(lower);
                    rec.setUpper(upper);
                    rec.setStep(step);
                    rec.setResult(result);
                }
                
                model.setValueAt(String.format("%.6f", result), selectedRow, 3);
                
            } catch (NumberFormatException ex) {
                javax.swing.JOptionPane.showMessageDialog(this, "Ошибка в данных строки!");
            }
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Выберите строку для вычисления!");
        }
    }

private double calculateIntegral(double a, double b, double h) {
    java.util.function.DoubleUnaryOperator f = x -> 1/x;
    
    double sum = 0;
    double currentX = a;
    
    while (currentX < b) {
        double nextX = currentX + h;

        if (nextX > b) {
            h = b - currentX;
            nextX = b;
        }

        sum += (f.applyAsDouble(currentX) + f.applyAsDouble(nextX)) * h / 2.0;
        
        currentX = nextX;
    }
    
    return sum;
    }//GEN-LAST:event_calculateActionPerformed

    @SuppressWarnings("empty-statement")
    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:
        String numberPattern = "-?\\d+(\\.\\d+)?";
    
    if (verhpor.getText().isEmpty() || nizpor.getText().isEmpty() || shag.getText().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Заполните все поля!", "Ошибка", JOptionPane.ERROR_MESSAGE);
        return;
    }
    
    // Проверка на корректность числового формата
    if (!verhpor.getText().matches(numberPattern) || 
        !nizpor.getText().matches(numberPattern) || 
        !shag.getText().matches(numberPattern)) {
        JOptionPane.showMessageDialog(this, "Введите числовые значения!", "Ошибка", JOptionPane.ERROR_MESSAGE);
        return;
    }
    
        double lower = Double.parseDouble(nizpor.getText());
        double upper = Double.parseDouble(verhpor.getText());
        double step = Double.parseDouble(shag.getText());

        if (lower >= upper) {
            JOptionPane.showMessageDialog(this, "Нижний порог должен быть меньше верхнего!", "Ошибка", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (step <= 0) {
            JOptionPane.showMessageDialog(this, "Шаг должен быть положительным числом!", "Ошибка", JOptionPane.ERROR_MESSAGE);
            return;
        }


        RecIntegral record = new RecIntegral(lower, upper, step, 0);
            records.add(record);

        DefaultTableModel tblModel = (DefaultTableModel) tabl.getModel();
        tblModel.addRow(new Object[] {lower, upper, step});
 
        verhpor.setText("");
        nizpor.setText("");
        shag.setText("");

    
    }//GEN-LAST:event_saveActionPerformed

    private void verhporActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verhporActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_verhporActionPerformed

    private void fillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fillActionPerformed
        // TODO add your handling code here:
         DefaultTableModel model = (DefaultTableModel) tabl.getModel();
        
        model.setRowCount(0);
        
        // Заполняем данными из коллекции
        for (RecIntegral rec : records) {
            String result = rec.getResult() == 0 ? "" : String.format("%.6f", rec.getResult());
            model.addRow(new Object[]{
                rec.getLower(),
                rec.getUpper(),
                rec.getStep(),
                result
            });
        }  
    }//GEN-LAST:event_fillActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:
        
        DefaultTableModel model = (DefaultTableModel) tabl.getModel();
        model.setRowCount(0);

    }//GEN-LAST:event_clearActionPerformed

    private void nizporActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nizporActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nizporActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, (UnsupportedLookAndFeelException) ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new NewJFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton calculate;
    private javax.swing.JButton clear;
    private javax.swing.JButton delete;
    private javax.swing.JButton fill;
    private javax.swing.JTextField nizpor;
    private javax.swing.JLabel np;
    private javax.swing.JButton save;
    private javax.swing.JLabel sh;
    private javax.swing.JTextField shag;
    private javax.swing.JTable tabl;
    private javax.swing.JScrollPane tablica;
    private javax.swing.JTextField verhpor;
    private javax.swing.JLabel vp;
    // End of variables declaration//GEN-END:variables

}
